name = "rich-presence-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "PRESENCE", class_name = "PresenceDurableObject" }
]

[[migrations]]
tag = "v1"
new_classes = ["PresenceDurableObject"]

[vars]
FRONTEND_URL = "http://localhost:3070"

[[env.production.vars]]
FRONTEND_URL = "https://your-frontend-domain.com"
